name: Continuous Integration

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Prepare Maven
        run: chmod +x mvnw
      - name: Clean
        run: ./mvnw clean
      - name: Build
        run: ./mvnw verify -DskipTests
      - name: Test
        run: ./mvnw test
